apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend
  namespace: default
spec:
  project: default
  source:
    repoURL: https://github.com/my-org/backend.git
    path: manifests
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: default
