apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: default
spec:
  project: default
  source:
    repoURL: https://github.com/pouriajalilian/frontend.git
    path: ./
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: default
